language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7

install:
  - pip install Django==$DJANGO_VERSION
  - pip install git+https://github.com/vinyll/jingo.git@django17

script:
  - python setup.py test
